<?php

namespace ContainerBsQLxzs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMinimunSignatureCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MinimunSignatureCommand' shared autowired service.
     *
     * @return \App\Command\MinimunSignatureCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'MinimunSignatureCommand.php';

        $container->privates['App\\Command\\MinimunSignatureCommand'] = $instance = new \App\Command\MinimunSignatureCommand();

        $instance->setName('app:minimun_signature');

        return $instance;
    }
}
