<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEhV7aD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEhV7aD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBEhV7aD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBEhV7aD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBEhV7aD\App_KernelDevDebugContainer([
    'container.build_hash' => 'BEhV7aD',
    'container.build_id' => 'bd5e2e4e',
    'container.build_time' => 1646647624,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEhV7aD');
