<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKwTBvpq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKwTBvpq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKwTBvpq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKwTBvpq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKwTBvpq\App_KernelDevDebugContainer([
    'container.build_hash' => 'KwTBvpq',
    'container.build_id' => 'a2fe7b89',
    'container.build_time' => 1646643428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKwTBvpq');
